# ----
# Site

title: Friendly Veg
url: "https://friendlyveg.com"
baseurl:
google_analytics_key: G-642SN665XK
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Easy vegan recipes
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
# social:
#   name: Friendly Veg
#   links:
#     - https://github.com/CloudCannon/treat-jekyll-template

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Tiktok
  - Instagram
  - YouTube

_options:
  author_image:
    width: 400
    height: 400
